name: CI

on: [push, pull_request]

jobs:
  format:
    name: Format and compile with warnings as errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.x
          elixir-version: 1.18.x

      - name: Install dependencies
        run: mix deps.get

      - name: Run "mix format"
        run: mix format --check-formatted

      - name: Compile with --warnings-as-errors
        run: mix compile --warnings-as-errors

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - erlang: 26.x
            elixir: 1.15.x
          - erlang: 27.x
            elixir: 1.18.x
    steps:
      - uses: actions/checkout@v4

      - name: Install OTP and Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.erlang}}
          elixir-version: ${{matrix.elixir}}

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test --trace
