name: CI

on: [push, pull_request]

jobs:
  format:
    name: Format and compile with warnings as errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 23.0
          elixir-version: 1.11.2

      - name: Install dependencies
        run: mix deps.get

      - name: Run "mix format"
        run: mix format --check-formatted

      - name: Compile with --warnings-as-errors
        run: mix compile --warnings-as-errors

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - erlang: 23.0
            elixir: 1.11.2
          - erlang: 22.3
            elixir: 1.9.4
    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.erlang}}
          elixir-version: ${{matrix.elixir}}

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test --trace